export const achievements = [
    {
        code: 'firstBoard',
        title: 'Опять школа?',
        description: 'Создайте свою первую доску',
        goal: 1,
    },
    {
        code: 'boardBuilder',
        title: 'Архитектор',
        description: 'Создайте 5 досок',
        goal: 5,
    },
    {
        code: 'boardCollector',
        title: 'Коллекционер',
        description: 'Создайте 15 досок',
        goal: 15,
    },
    {
        code: 'firstColumn',
        title: 'Первый столбец',
        description: 'Создайте свою первую колонку',
        goal: 1,
    },
    {
        code: 'organizer',
        title: 'Систематизатор',
        description: 'Создайте 10 колонок',
        goal: 10,
    },
    {
        code: 'firstCard',
        title: 'Первый шаг',
        description: 'Создайте свою первую задачу',
        goal: 1,
    },
    {
        code: 'tenTasksCompleted',
        title: 'Я уже смешарик',
        description: 'Выполните первые 10 задач',
        goal: 10,
    },
    {
        code: 'fiftyTasksCompleted',
        title: 'На полпути',
        description: 'Выполните 50 задач',
        goal: 50,
    },
    {
        code: 'hundredTasksCompleted',
        title: 'Сотня за плечами',
        description: 'Выполните 100 задач',
        goal: 100,
    },
    {
        code: 'fiveHundredTasksCompleted',
        title: 'Легенда продуктивности',
        description: 'Выполните 500 задач',
        goal: 500,
    },
    {
        code: 'weekStreak',
        title: 'Неделя без пропусков',
        description: 'Выполняйте задачи 7 дней подряд',
        goal: 7,
    },
    {
        code: 'monthStreak',
        title: 'Железная воля',
        description: 'Выполняйте задачи 30 дней подряд',
        goal: 30,
    },
    {
        code: 'firstMessage',
        title: 'Социализация',
        description: 'Напишите первое сообщение в чате',
        goal: 1,
    },
    {
        code: 'chatty',
        title: 'Говорун',
        description: 'Напишите 50 сообщений',
        goal: 50,
    },
    {
        code: 'firstInvite',
        title: 'Командный игрок',
        description: 'Пригласите первого участника в доску',
        goal: 1,
    },
    {
        code: 'teamBuilder',
        title: 'Строитель команды',
        description: 'Пригласите 10 участников в свои доски',
        goal: 10,
    },
];
